# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SatelliteImageLoader
                                 A QGIS plugin
 Use to load Images from Sentinel-1 GRD, Sentinel-2 Level-2A or Suomi-NPP VIIRS Day-Night-Band
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-07
        copyright            : (C) 2023 by jteske
        email                : jteske@hm.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SatelliteImageLoader class from file SatelliteImageLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .satellite_image_loader import SatelliteImageLoader
    return SatelliteImageLoader(iface)
